env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb/hooks
  - plugin:prettier/recommended
settings:
  import/resolver:
    node:
      paths:
        - src/
      extensions:
        - .js
        - .jsx
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules: {}
