env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
  - plugin:node/recommended
parserOptions:
  ecmaVersion: 12
rules: { indent: ['error', 'tab'] }
