env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
  - plugin:node/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
plugins:
  - prettier
